// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Options.Models;

namespace Options.Migrations
{
    [DbContext(typeof(OptionsDBContext))]
    [Migration("20200928204007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Options.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AveragePrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comission")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Profit")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockPriceAtSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
